
DROP TABLE ORDR CASCADE CONSTRAINTS;



DROP TABLE CAR CASCADE CONSTRAINTS;



DROP TABLE CAR_TYPE CASCADE CONSTRAINTS;



CREATE TABLE CAR
(
	ID		  INTEGER  NOT NULL ,
	MODEL		  VARCHAR2(255)  NOT NULL ,
	GOV_NUMBER	  VARCHAR2(9)  NOT NULL ,
	RUNNING		  INTEGER  NULL ,
	TYPEID		  INTEGER  NOT NULL 
);



CREATE UNIQUE INDEX XPKCar ON CAR
(ID  ASC);



ALTER TABLE CAR
	ADD CONSTRAINT  XPKCar PRIMARY KEY (ID);



CREATE UNIQUE INDEX XAK1Car ON CAR
(GOV_NUMBER  ASC);



CREATE TABLE CAR_TYPE
(
	ID		  INTEGER  NOT NULL ,
	NAME		  VARCHAR2(255)  NOT NULL ,
	SEAT_CAP	  INTEGER  NOT NULL ,
	COST_PER_KM	  INTEGER  NOT NULL 
);



CREATE UNIQUE INDEX XPKCarTYPE ON CAR_TYPE
(ID  ASC);



ALTER TABLE CAR_TYPE
	ADD CONSTRAINT  XPKCarTYPE PRIMARY KEY (ID);



CREATE UNIQUE INDEX XAK1CAR_TYPE ON CAR_TYPE
(NAME  ASC);



CREATE TABLE ORDR
(
	ID		  INTEGER  NOT NULL ,
	TIME_ORD	  DATE  NULL ,
	TIME_DONE	  DATE  NULL ,
	ADDR_DEP	  VARCHAR2(255)  NOT NULL ,
	ADDR_DEST	  VARCHAR2(255)  NOT NULL ,
	PASSENGERS	  INTEGER  NOT NULL ,
	DISTANCE	  INTEGER  NULL ,
	COST		  INTEGER  NULL ,
	PHONE		  INTEGER  NOT NULL ,
	CARID		  INTEGER  NOT NULL ,
	COMPLETED	  NUMBER(1)  NOT NULL 
);



CREATE UNIQUE INDEX XPKOrder ON ORDR
(ID  ASC);



ALTER TABLE ORDR
	ADD CONSTRAINT  XPKOrder PRIMARY KEY (ID);



ALTER TABLE CAR
	ADD (CONSTRAINT  R_3 FOREIGN KEY (TYPEID) REFERENCES CAR_TYPE(ID));



ALTER TABLE ORDR
	ADD (CONSTRAINT  R_4 FOREIGN KEY (CARID) REFERENCES CAR(ID));


